### PR TITLE
Pass config of a named paragraph to renderer

### PR DESCRIPTION
**Pull request by Altai-man**
Pod paragraph in named blocks can be flexibly configured, but
a paragraph renderer won't see the config of its parent the way it
is not passed now.

We probably have to do this everywhere, but lazy evaluation of
such cases is likely a better idea to avoid clutter and rapid perf bumps.

This is a second step of https://github.com/Raku/doc/pull/3693

### CODE REVIEW

**Review by JJ — APPROVED** [review]
Looks fine. Thanks!

**Comment by JJ** [comment]
As usual also, a test would be very much appreciated.

**Comment by Altai-man** [comment]
Aye!

**Review by JJ — APPROVED** [review]
Looks fine. Thanks!

**Pull request merged**
